version: "2"

services:
  accreditation:
    image: accreditation
    build: .
    ports:
      - "9000:3000"
    volumes:
      - .:/opt/webapps/app
      - ./shared/ca:/opt/ca
      - tmp:/opt/webapps/app/tmp/
    links:
      - database
    environment:
      DATABASE_HOST: database
      POSTGRES_USER: ​postgres
      POSTGRES_PASSWORD: some-long-secure-password
      POSTGRES_DB: db
      ACCREDITATION_CENTER_DATABASE_PASSWORD: some-long-secure-password
      SECRET_KEY_BASE: 5a1644fba6573a021373273be0ad901ec9b4a82d57efdc69831c0ad94644c42290147672a1b389e13f30251163f3d90b9245ccb2ae46f7f7fe8acb54b2ef76fe
    command: bash -c "rm -f tmp/pids/server.pid && bundle update --bundler && bundle exec rails server -b 0.0.0.0"
    restart: always

  database:
    image: postgres:13.2
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: some-long-secure-password
      POSTGRES_DB: db
    ports: 
      - 9091:5432
    restart: always

volumes:
  db:
  tmp: