FROM internetee/ruby:2.7-buster
LABEL org.opencontainers.image.source=https://github.com/internetee/accreditation_center
ARG RAILS_ENV
ARG SECRET_KEY_BASE

ENV RAILS_ENV "$RAILS_ENV"
ENV SECRET_KEY_BASE "$SECRET_KEY_BASE"

RUN mkdir -p /opt/webapps/app/tmp/pids
WORKDIR /opt/webapps/app
COPY . .
RUN gem install bundler && bundle update --bundler && bundle config set without 'development test' && bundle install
