name: Github Testing
on: [push]


jobs:
  test:
    services:
      postgres:
        image: postgres:12
        ports: ["5432:5432"]
        env:
          POSTGRES_PASSWORD: some-long-secure-password
          POSTGRES_USERNAME: ​postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04]
        ruby: [ 2.7  ]
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ endsWith(matrix.ruby, 'head') || matrix.ruby == 'debug' }}
    steps:

    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: config bundler
      run:  |
        bundle config set without 'development staging production'
        bundle config set deployment '[secure]'
        bundle env
        head -n1 $(which bundle)

    - name: Run Tests
      env:
        PG_DATABASE: postgres
        PG_HOST: localhost
        PG_USER: postgres
        PG_PASSWORD: password
        PG_PORT: ${{ job.services.postgres.ports[5432] }}
        RAILS_ENV: test
        COVERAGE: true
        DISABLE_SPRING: 1
      run: |
        cp config/database.yml.sample config/database.yml
        bundle exec rake db:setup:all
        bundle exec rails test test/*

    - uses: actions/upload-artifact@v2.2.4
      with:
        name: coverage-${{ matrix.ruby }}
        path: coverage/codeclimate.${{ matrix.ruby }}.json
